#!/bin/bash

sudo aptitude install mysql-server
sudo aptitude safe-upgrade
sudo aptitude install  \
  apache2  \
  apt-rdepends  \
  auctex  \
  bash-doc  \
  build-essential  \
  clisp  \
  emacs  \
  exiv2  \
  exuberant-ctags  \
  ffmpeg  \
  g++  \
  gimp  \
  gstreamer-tools  \
  guile-1.8  \
  id3tool  \
  iftop  \
  inkscape  \
  iotop  \
  libapache2-mod-php5  \
  libconfig-any-perl  \
  libdate-calc-perl  \
  libterm-readline-gnu-perl  \
  luajit  \
  maxima  \
  mplayer-nogui  \
  octave3.2  \
  openjdk-6-jdk  \
  perl-doc  \
  perlconsole  \
  php5  \
  php5-mysql  \
  php5-sqlite  \
  python-scipy  \
  r-recommended  \
  rlwrap  \
  ruby-full  \
  rubybook  \
  rubygems  \
  texlive-full  \
  ttf-inconsolata  \
  ttf-mgopen  \
  ttf-mscorefonts-installer  \
  vorbis-tools  \
  wordpress  \
  xsel  \
  youtube-dl

sudo aptitude safe-upgrade
