#!/bin/bash

ln -sf $conf/vim/vimrc               $HOME/.vimrc
ln -sf $conf/vim/vim                 $HOME/.vim

ln -sf $conf/bash/bashrc             $HOME/.bashrc
ln -sf $conf/bash/bash_aliases       $HOME/.bash_aliases
ln -sf $conf/bash/bash_profile       $HOME/.bash_profile

ln -sf $conf/git/gitconfig           $HOME/.gitconfig

rm $HOME/.vim/vim
