#!/bin/bash

sudo aptitude install acpitool compizconfig-settings-manager git-core gnome-themes-extras htop openssh-server vim-gnome

/home/joycetipping/configuration/gnome/gconf apply

ln -s /home/joycetipping/configuration/vim/vim            /home/joycetipping/.vim
ln -s /home/joycetipping/configuration/vim/vimrc          /home/joycetipping/.vimrc
ln -s /home/joycetipping/configuration/emacs              /home/joycetipping/.emacs

ln -s /home/joycetipping/configuration/bash/bashrc        /home/joycetipping/.bashrc
ln -s /home/joycetipping/configuration/bash/bash_aliases  /home/joycetipping/.bash_aliases
ln -s /home/joycetipping/configuration/bash/profile       /home/joycetipping/.profile

ln -s /home/joycetipping/configuration/xinitrc            /home/joycetipping/.xinitrc

ln -s /home/joycetipping/configuration/texmf-var          /home/joycetipping/.texmf-var
