#!/usr/bin/perl

open my $file, '<', '/home/joycetipping/library/notes/packages.txt';

# The original regex
#my @packages = sort grep s/^\s+(.+)\s*$/$1/, <$file>;

# This regex allows you to have comments with the | symbol. The s flag is to match the newline at the end.
my @packages = sort grep s/^\s+([^|\s]+).*$/$1/s, <$file>;

print join "\n", @packages;
