#!/bin/bash
# Sudo this script

# A script for installing my packages; intended to run overnight.

# Install these first they require interaction (prompt for password, accept license), which will block the rest of the process
aptitude install mysql-server ttf-mscorefonts-installer

# Install the rest of the packages, upgrading before and after.
aptitude update
aptitude safe-upgrade

aptitude install $(./compile-packages);

aptitude update
aptitude safe-upgrade

# Set up symlink in /var/www/ to my local public_html
ln -s $HOME/public_html/ /var/www/jt
