"Basic

colorscheme nightflower

set autoindent
set expandtab
set foldcolumn=2
set foldmethod=marker
set hidden
set hlsearch
set ignorecase
set incsearch
set list
set listchars=tab:\ \ ,trail:·
set modeline
set modelines=5
set mouse=a
set nojoinspaces
set nowrap
set number
set ruler
set runtimepath+=~/.vim/plugins/*
set shiftwidth=2
set showcmd
set tabstop=2
set tags=./tags;/
set title

let mapleader = " "

nnoremap s o<ESC>
nnoremap S O<ESC>
nnoremap ' `
nnoremap ` '
nnoremap <S-h> gT
nnoremap <S-l> gt
nnoremap <C-h> :call TabSlideLeft()<CR>
nnoremap <C-l> :call TabSlideRight()<CR>
nnoremap <F7>  :call ToggleTerminalCopyPaste()<CR>

com Helptags call GetHelpTags()

filetype plugin on
au BufRead,BufNewFile *.gnarly   set filetype=gnarly
au BufRead,BufNewFile *.markdown set filetype=markdown
au BufRead,BufNewFile *.scala    set filetype=scala

function! SyntaxItem()
  echo synIDattr(synID(line("."),col("."),1),"name")
endfunction

function! ToggleTerminalCopyPaste()
  if &paste == 0
    set mouse=
    set paste
    set nonumber
    echo "Terminal copy & paste enabled"
  else
    set mouse=a
    set nopaste
    set number
    echo "Terminal copy & paste disabled"
  endif
endfunction

function! TabSlideLeft()
  " Get current tab number (one-based)
  let current = tabpagenr()

  " Move tab only if it's not the first
  " We're subtracting 2 because the "tabm" command is zero-based.
  if current > 1
    exec "tabm" . (current - 2)
  endif
endfunction

function! TabSlideRight()
  " Get current tab number (one-based)
  let current = tabpagenr()

  " Move tab. Since tabm is zero-based, we do not need to add 1.
  exec "tabm " . current
endfunction

function! GetHelpTags()
  let doc_dirs = filter(split(system('find ~/.vim/ | grep -e doc$'), '\n'), 'isdirectory(v:val)')
  for dir in doc_dirs
    exec "helptags" . dir
  endfor
endfunction

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

"Plugins

"Ctags
"map <C-\> :tab split<CR>:exec("tag ".expand("<cword>"))<CR>  "Open in new tab
map <C-\> :vsp<CR>:exec("tag ".expand("<cword>"))<CR>        "Open in vertical split

"Nerdtree
map <F2> :NERDTreeToggle<CR>

"Tlist
map <F3> :TlistToggle<CR>

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

"Special setups and operating systems

"gVim on Windows
syntax on
set bs=2
