"Basic
set autoindent
set expandtab
set foldcolumn=2
set foldmethod=marker
set hlsearch
set ignorecase
set incsearch
set modeline
set modelines=5
set mouse=a
set nojoinspaces
set nowrap
set number
set shiftwidth=2
set showcmd
set tabstop=2
set tags=./tags;/
set title

"Key Mappings
nnoremap s o<ESC>
nnoremap S O<ESC>
map <C-\> :tab split<CR>:exec("tag ".expand("<cword>"))<CR>  "C-\  Open definition in new tab
"map <A-]> :vsp <CR>:exec("tag ".expand("<cword>"))<CR>       "A-]  Open definition in vertical split

"Folds
"au BufWinLeave        *          mkview
"au BufWinEnter        *          silent loadview
"au BufWrite           *          mkview
"au BufRead            *          silent loadview
"au BufRead,BufNewFile *.txt      set foldmethod=indent
hi Folded     ctermbg=15
hi FoldColumn ctermbg=15

"Special Filetypes
au BufRead,BufNewFile *.cltex    set filetype=cltex
au BufRead,BufNewFile *.gnarly   set filetype=gnarly
au BufRead,BufNewFile *.hx       set filetype=haxe
au BufRead,BufNewFile *.ljs      set filetype=ljs
au BufRead,BufNewFile *.lp       set filetype=lispwithparagraphs
au BufRead,BufNewFile *.ocamltex set filetype=ocamltex
au BufRead,BufNewFile *.scala    set filetype=scala

"Ctags
