#!/bin/bash

nightflower='{
    "Ansi 0 Color" =         {
        "Blue Component" = 0;
        "Green Component" = 0;
        "Red Component" = 0;
    };
    "Ansi 1 Color" =         {
        "Blue Component" = 1;
        "Green Component" = 0;
        "Red Component" = 1;
    };
    "Ansi 10 Color" =         {
        "Blue Component" = 0;
        "Green Component" = 1;
        "Red Component" = 0;
    };
    "Ansi 11 Color" =         {
        "Blue Component" = "0.3333333";
        "Green Component" = 1;
        "Red Component" = 1;
    };
    "Ansi 12 Color" =         {
        "Blue Component" = 1;
        "Green Component" = "0.6666667";
        "Red Component" = "0.4";
    };
    "Ansi 13 Color" =         {
        "Blue Component" = "0.9333333";
        "Green Component" = "0.5333334";
        "Red Component" = "0.9333333";
    };
    "Ansi 14 Color" =         {
        "Blue Component" = 1;
        "Green Component" = 1;
        "Red Component" = "0.3333333432674408";
    };
    "Ansi 15 Color" =         {
        "Blue Component" = 1;
        "Green Component" = "0.8";
        "Red Component" = 1;
    };
    "Ansi 2 Color" =         {
        "Blue Component" = 0;
        "Green Component" = 1;
        "Red Component" = 0;
    };
    "Ansi 3 Color" =         {
        "Blue Component" = "0.3333333";
        "Green Component" = 1;
        "Red Component" = 1;
    };
    "Ansi 4 Color" =         {
        "Blue Component" = 1;
        "Green Component" = "0.6666667";
        "Red Component" = "0.4";
    };
    "Ansi 5 Color" =         {
        "Blue Component" = "0.9333333";
        "Green Component" = "0.5333334";
        "Red Component" = "0.9333333";
    };
    "Ansi 6 Color" =         {
        "Blue Component" = 1;
        "Green Component" = 1;
        "Red Component" = 0;
    };
    "Ansi 7 Color" =         {
        "Blue Component" = 1;
        "Green Component" = "0.8";
        "Red Component" = 1;
    };
    "Ansi 8 Color" =         {
        "Blue Component" = 0;
        "Green Component" = 0;
        "Red Component" = 0;
    };
    "Ansi 9 Color" =         {
        "Blue Component" = 1;
        "Green Component" = 0;
        "Red Component" = 1;
    };
    "Anti Alias" = 1;
    "Background Color" =         {
        "Blue Component" = 0;
        "Green Component" = 0;
        "Red Component" = 0;
    };
    Blur = 0;
    "Bold Color" =         {
        "Blue Component" = 0;
        "Green Component" = 0;
        "Red Component" = 1;
    };
    Columns = 210;
    "Cursor Color" =         {
        "Blue Component" = 1;
        "Green Component" = "0.8";
        "Red Component" = 1;
    };
    "Cursor Text Color" =         {
        "Blue Component" = 1;
        "Green Component" = "0.8";
        "Red Component" = 1;
    };
    "Disable Bold" = 1;
    Font = "Monaco 10";
    "Foreground Color" =         {
        "Blue Component" = 1;
        "Green Component" = "0.8";
        "Red Component" = 1;
    };
    "Horizontal Character Spacing" = 1;
    NAFont = "Monaco 10";
    Rows = 110;
    "Selected Text Color" =         {
        "Blue Component" = 0;
        "Green Component" = 0;
        "Red Component" = 0;
    };
    "Selection Color" =         {
        "Blue Component" = 1;
        "Green Component" = "0.8353000283241272";
        "Red Component" = "0.7098000049591064";
    };
    Transparency = "0.15";
    "Vertical Character Spacing" = 1;
}'

# Add display profile
defaults write net.sourceforge.iTerm Displays -dict-add nightflower "$nightflower"
echo "nightflower display profile added"
