# vim: syntax=sh :

# Exports
export EDITOR=/usr/bin/vim

# Aliases
alias cpl='cp -d'
alias remove='/bin/rm'
alias rm='echo Use remove'
alias sudojt='sudo -u joycetipping'
alias sus='sudo pm-suspend'

alias u='cd ../'
alias u2='cd ../../'
alias u3='cd ../../../'
alias u4='cd ../../../../'
alias u5='cd ../../../../../'
alias u6='cd ../../../../../../'
alias u7='cd ../../../../../../../'
alias u8='cd ../../../../../../../../'

alias aliases='vim $HOME/projects/configuration/bash/bash_aliases'
alias luajit='luajit-2.0.0-beta2'
alias musings='vim $HOME/projects/musings/2010.txt'
alias nodedoc='man $HOME/projects/github/nodejs/doc/node.1'
alias notes='cd $HOME/library/notes/'
alias vt='vim -t'

# Bash prompt:
. $HOME/projects/configuration/bash/prompt

# RVM
# [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"  # This loads RVM into a shell session.
# Haxe
HAXE_LIBRARY_PATH="$HOME/library/programs/haxe/haxe/std:."



# Socialmedia
alias clients='ssh joyce@clients.socialmedia.com'
alias flafdoc='evince $HOME/projects/socialmedia/platform/flaf-1.0/framework/docs/developer/dev-guide.pdf'

alias adclient='cd $HOME/projects/socialmedia/adops/adclient/'
alias adops='cd $HOME/projects/socialmedia/adops/'
alias ads='cd $HOME/projects/socialmedia/adops/ads/'
alias hours='vim $HOME/projects/socialmedia/hours/dec.txt'
alias platform='cd $HOME/projects/socialmedia/platform/'
alias sm='cd $HOME/projects/socialmedia/'
alias stax='cd $HOME/projects/socialmedia/platform/stax/'
alias wiki='cd $HOME/projects/socialmedia/adops/wiki/'
