# ~/.bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Define two very important variables
export home="$HOME/home"
export conf="$home/projects/configuration"

# Include user's private bin
if [[ -d "$home/bin" ]]; then PATH="$PATH:$home/bin"; fi

# Bash prompt
source "$conf/bash/prompt"

# Terminal settings
export EDITOR="/usr/bin/vim"
export VISUAL="/usr/bin/vim"
export CLICOLOR=true  # colored output
export LC_CTYPE='en_US.utf-8'
export TERM='xterm-color'

# Bash history
HISTCONTROL=ignoredups:ignorespace    # Don't put duplicate lines in the history.
shopt -s histappend                   # Append to the history file, don't overwrite it
HISTSIZE=1000
HISTFILESIZE=2000

# Source bash includes
if [[ -f "$conf/bash/includes/aliases"   ]]; then source "$conf/bash/includes/aliases";   fi
if [[ -f "$conf/bash/includes/foraker"   ]]; then source "$conf/bash/includes/foraker";   fi
if [[ -f "$conf/bash/includes/functions" ]]; then source "$conf/bash/includes/functions"; fi
if [[ -f "$conf/bash/includes/programs"  ]]; then source "$conf/bash/includes/programs";  fi
