# vim: syntax=sh :

# Exports
export EDITOR=/usr/bin/vim

# Aliases
alias cpl='cp -d'
alias remove='/bin/rm'
alias rm='echo Use remove'
alias sudojt='sudo -u joycetipping'
alias sus='sudo pm-suspend'

alias u='cd ../'
alias u2='cd ../../'
alias u3='cd ../../../'
alias u4='cd ../../../../'
alias u5='cd ../../../../../'
alias u6='cd ../../../../../../'
alias u7='cd ../../../../../../../'
alias u8='cd ../../../../../../../../'

alias luajit='luajit-2.0.0-beta2'
alias nodedoc='man /home/joycetipping/projects/github/node/doc/node.1'
alias vt='vim -t'
alias musings='vim /home/joycetipping/projects/musings/2010.txt'

# Bash prompt:
. /home/joycetipping/projects/configuration/bash/prompt

# RVM
# [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"  # This loads RVM into a shell session.





# Socialmedia
alias clients='ssh joyce@clients.socialmedia.com'
alias flafdoc='evince /home/joycetipping/projects/socialmedia/platform/flaf-1.0/framework/docs/developer/dev-guide.pdf'

alias ads='cd /home/joycetipping/projects/socialmedia/ads/'
alias display='cd /home/joycetipping/projects/socialmedia/platform/ad-display/src/main/haxe/socialmedia/display'
alias platform='cd /home/joycetipping/projects/socialmedia/platform/'
alias sm='cd /home/joycetipping/projects/socialmedia/'
alias hours='vim /home/joycetipping/projects/socialmedia/hours/nov.txt'
