#!/bin/bash
# WTFPL license ... cheers!

# The original
#export PS1='\[\033[1;32m\]\h\[\033[1;34m\]\W\[\033[0;0m\] '

# My attempts
export PS1='\[\033[1;35m\]\h\[\033[1;31m\]\W\[\033[0;0m\] '
#export PS1='\[\033[1;35m\]\h\[\033[1;0m\]\W* '
#export PS1='\[\033[1;35m\][\h]\W\[\033[0;0m\] '
#export PS1='\h\[\033[1;35m\]\W\[\033[0;0m\] '
