#!/bin/bash

cat wp.sql | mysql -u root -p

mysql -u root -p <<EOF
grant all privileges on wp_demo.*     to "wp_demo"@"localhost"     identified by "wp_demo";
grant all privileges on wp_lifeblog.* to "wp_lifeblog"@"localhost" identified by "wp_lifeblog";
grant all privileges on wp_spencer.*  to "wp_spencer"@"localhost"  identified by "wp_spencer";
grant all privileges on wp_techblog.* to "wp_techblog"@"localhost" identified by "wp_techblog";
grant all privileges on wp_test.*     to "wp_test"@"localhost"     identified by "wp_test";
EOF
